export type Block =
  | { kind: "text"; text: string }
  | { kind: "heading"; text: string }
  | { kind: "code"; code: string }
  | { kind: "note"; text: string }
  | { kind: "list"; items: string[] };

export type Chapter = {
  id: string;
  title: string;
  group: string;
  summary: string;
  wip?: boolean;
  blocks: Block[];
};

export const GUIDE_CHAPTERS: Chapter[] = [
  {
    id: "introduction",
    title: "Introduction",
    group: "Language",
    summary: "What Tera is and the engine it runs on.",
    blocks: [
      { kind: "text", text: "Tera is a statically typed language for numerical and machine-learning work. Its syntax is offside — blocks open with `:` and a deeper indent, with no braces and no semicolons — and the type checker runs over your code before any of it executes. Tensors, automatic differentiation, models, DataFrames, reactive state, and charts are part of the language, not packages you import." },
      { kind: "text", text: "Tera runs on its own engine. Source is type-checked, lowered to register bytecode, and executed by a virtual machine that tiers up as code gets hot: the interpreter runs first, a baseline compiler takes over next, and a speculative optimizer compiles the hottest functions to WebAssembly. Long-running loops are swapped to optimized code mid-run through on-stack replacement, speculation that turns out wrong is deoptimized back to the interpreter, and inline caches and a generational garbage collector keep everyday code fast." },
      { kind: "code", code: "fn greet(name: string) -> string:\n  return \"Hello, \" + name\n\nprint(greet(\"Tera\"))" },
      { kind: "list", items: [
        "**Checked before it runs** — the type checker reports mistakes ahead of execution, not partway through a computation.",
        "**Offside syntax** — `:` and indentation define every block; no braces, no semicolons.",
        "**Numerics built in** — `tensor`, `model`, `DataFrame`, `signal`, and `chart` are part of the language.",
        "**Tiering JIT to WebAssembly** — hot functions are compiled and hot loops are replaced in place while they run.",
      ] },
      { kind: "note", text: "Every code block in these docs is real Tera. Copy one into a notebook cell and run it." },
    ],
  },
  {
    id: "values-and-types",
    title: "Values & types",
    group: "Language",
    summary: "Primitives, the int/float split, numbers, and strings.",
    blocks: [
      { kind: "text", text: "Tera's primitives are `int`, `float`, `string`, `bool`, and the two empty values `null` and `undefined`. Keeping `int` and `float` as separate types is deliberate: numeric and tensor code cares whether a value is a whole number or a real one, and the checker holds you to the distinction rather than blurring them into a single number type. A binding takes the type of the value you give it, and you can spell that type out with `name: Type = value` whenever you want the annotation for clarity or to catch a mistake early." },
      { kind: "code", code: "quantity: int = 3\nratio: float = 0.5\nname: string = \"ada\"\nready: bool = true\nprint(quantity, ratio, name, ready)" },
      { kind: "text", text: "`typeof` reports the runtime kind of a value as a string — handy for a quick check, and for seeing how a literal was classified." },
      { kind: "code", code: "print(typeof 5, typeof \"s\", typeof true)" },
      { kind: "heading", text: "Numbers" },
      { kind: "text", text: "The decimal point is what separates the two number types: `3` is an `int`, while `3.0` is a `float`. Division, remainder with `%`, and exponentiation with `**` all read as usual, and numbers carry formatting helpers such as `to_fixed`, which rounds to a fixed number of decimal places and returns the result as a string." },
      { kind: "code", code: "print(7 / 2, 7 % 2, 2 ** 8)\nprint((3.14159).to_fixed(2))" },
      { kind: "heading", text: "Strings" },
      { kind: "text", text: "Ordinary strings use double quotes, while backtick templates let you drop any expression inline with `${...}` — the cleanest way to build a message out of several values without a chain of `+`." },
      { kind: "code", code: "owner = \"Ada\"\nbalance = 120\nprint(`${owner} has ${balance}`)" },
      { kind: "text", text: "Strings come with the usual library of methods, spelled in `snake_case` like every method in Tera. They return new strings rather than changing the original in place, so you can chain them freely:" },
      { kind: "list", items: [
        "`to_upper_case()` / `to_lower_case()` — change case.",
        "`trim()` — drop surrounding whitespace.",
        "`slice(start, end)` — take a substring by index.",
        "`includes(sub)` / `starts_with(prefix)` — test for a substring.",
        "`replace_all(from, to)` — swap every occurrence.",
        "`repeat(n)` — repeat the string `n` times.",
      ] },
      { kind: "code", code: "print(\"ada\".to_upper_case())\nprint(\"HELLO\".to_lower_case())\nprint(\"  hi  \".trim())\nprint(\"hello\".slice(1, 3))" },
      { kind: "code", code: "print(\"hello\".includes(\"ell\"))\nprint(\"hello\".starts_with(\"he\"))\nprint(\"a-b-c\".replace_all(\"-\", \"+\"))\nprint(\"ab\".repeat(3))" },
      { kind: "note", text: "Passing an `int` where a `float` is expected is fine — the `int` widens automatically. The other direction is a checker error, since narrowing a `float` to an `int` would silently drop its fractional part." },
    ],
  },
  {
    id: "variables",
    title: "Variables & bindings",
    group: "Language",
    summary: "Introducing, updating, and destructuring values.",
    blocks: [
      { kind: "text", text: "Tera has no `let` or `var` keyword to introduce a variable — writing `name = value` for the first time is what creates the binding. Its type is inferred from the value, so from that point on the checker knows what the name holds; add an explicit `name: Type = value` when you want the annotation documented or enforced." },
      { kind: "code", code: "total = 0\npi = 3.14159\ntotal = total + pi\nprint(total)" },
      { kind: "text", text: "Assigning to a name that already exists updates it instead of creating a second binding. Compound operators like `+=` and `*=`, and the `++`/`--` steppers, update a binding in place. The type, though, is fixed at that first assignment — storing a value of an incompatible type later is a checker error, not a silent re-typing of the variable." },
      { kind: "code", code: "n = 10\nn += 5\nn *= 2\nprint(n)" },
      { kind: "code", code: "i = 0\ni++\ni++\nprint(i)" },
      { kind: "text", text: "Destructuring pulls values out of an array or object and binds them to names in one step — matching by position for arrays and by key for objects. The patterns nest, so you can reach several levels into a structure at once." },
      { kind: "code", code: "[a, b] = [1, 2]\n{ name } = { name: \"Ada\", score: 10 }\nprint(a, b, name)" },
      { kind: "code", code: "{ user: { name } } = { user: { name: \"Ada\" } }\nprint(name)" },
    ],
  },
  {
    id: "operators",
    title: "Operators",
    group: "Language",
    summary: "Arithmetic, logic, null-safety, and the ternary.",
    blocks: [
      { kind: "text", text: "Arithmetic behaves as you would expect from `+`, `-`, `*`, and `/`, with `**` for exponentiation and `%` for the remainder. Precedence follows the usual mathematical rules, and parentheses group subexpressions when you want to override it." },
      { kind: "code", code: "print(7 / 2, 7 % 2, 2 ** 8)" },
      { kind: "text", text: "Boolean logic reads as words — `and`, `or`, `not` — which many people find clearer inside a condition. The C-style forms `&&`, `||`, and `!` are accepted too and mean exactly the same thing, so use whichever fits the surrounding code." },
      { kind: "code", code: "ready = true\nif ready and not false:\n  print(\"go\")" },
      { kind: "text", text: "The ternary `cond ? a : b` picks between two values inline, evaluating only the branch it chooses — a compact alternative to a full `if`/`else` when you just need one of two expressions." },
      { kind: "code", code: "x = 7\nprint(x > 5 ? \"big\" : \"small\")" },
      { kind: "text", text: "The two null-aware operators deal with missing data gracefully: `??` supplies a fallback when the left side is `null` or `undefined` (but not when it is `0` or an empty string), and `?.` reads a property through a value that might be absent, yielding `undefined` instead of throwing." },
      { kind: "code", code: "config = { retries: null }\nprint(config.retries ?? 3)\nprint(config?.timeout)" },
      { kind: "heading", text: "Object & type operators" },
      { kind: "text", text: "A few operators work on objects and types directly: `in` tests whether a key is present, `delete` removes a key, and `instanceof` checks whether an object was built from a given class." },
      { kind: "code", code: "o = { a: 1, b: 2 }\nprint(\"a\" in o, \"z\" in o)\ndelete o.a\nprint(o)" },
      { kind: "code", code: "class Animal:\n  public constructor():\n    this.kind = \"animal\"\n\na = Animal()\nprint(a instanceof Animal)" },
    ],
  },
  {
    id: "control-flow",
    title: "Control flow",
    group: "Language",
    summary: "Branches, loops, switch, and error handling.",
    blocks: [
      { kind: "text", text: "`if`/`else` chooses between branches on a condition. Like every block in Tera's offside syntax, each arm opens with a `:` and a deeper indent — there are no braces, and the indentation itself is what defines the body." },
      { kind: "code", code: "score = 82\nif score >= 90:\n  print(\"A\")\nelse:\n  print(\"needs work\")" },
      { kind: "text", text: "Tera has two `for` loops, and the keyword between the name and the collection decides which. `for … of` walks the values of an array, string, or range, while `for … in` walks the keys of an object or the indices of an array." },
      { kind: "code", code: "total = 0\nfor n of range(1, 5):\n  total = total + n\nprint(total)" },
      { kind: "code", code: "for ch of \"abc\":\n  print(ch)" },
      { kind: "code", code: "for key in { a: 1, b: 2 }:\n  print(key)" },
      { kind: "text", text: "`while` repeats its body for as long as a condition stays true, re-checking it before each pass. Inside any loop, `break` stops it early and `continue` skips ahead to the next iteration." },
      { kind: "code", code: "i = 0\nwhile i < 3:\n  print(i)\n  i = i + 1" },
      { kind: "text", text: "`switch` compares a value against a series of `case` labels and runs the first that matches, with `default` as the catch-all. Cases fall through by design, so end each one with `break` unless you deliberately want execution to continue into the next case." },
      { kind: "code", code: "x = 2\nswitch x:\n  case 1:\n    print(\"one\")\n    break\n  case 2:\n    print(\"two\")\n    break\n  default:\n    print(\"other\")" },
      { kind: "text", text: "`throw` raises an error that unwinds the call stack until something catches it. A `try` block runs code that might throw, `catch` receives the error and recovers, and `finally` runs afterwards either way — the place for cleanup that must happen whether or not an error occurred." },
      { kind: "code", code: "try:\n  throw \"boom\"\ncatch e:\n  print(\"caught\", e)\nfinally:\n  print(\"done\")" },
    ],
  },
  {
    id: "functions",
    title: "Functions",
    group: "Language",
    summary: "Declarations, defaults, rest & spread, closures, and async.",
    blocks: [
      { kind: "text", text: "Declare a function with `fn`, a name, its parameters, and — after the `->` arrow — its return type. The parameter and return types are written out so every caller is checked against them, while the types of locals inside the body are inferred for you." },
      { kind: "code", code: "fn area(width: float, height: float) -> float:\n  return width * height\n\nprint(area(3.0, 4.0))" },
      { kind: "text", text: "A parameter can carry a default value, which makes it optional at the call site. Callers may also pass arguments by name instead of by position, which keeps a call readable when a function takes several options." },
      { kind: "code", code: "fn greet(name: string, greeting: string = \"Hello\") -> string:\n  return `${greeting}, ${name}`\n\nprint(greet(\"Ada\"))\nprint(greet(\"Ada\", greeting=\"Hi\"))" },
      { kind: "text", text: "A `...rest` parameter gathers any extra positional arguments into a single array, so a function can accept a variable number of them. The same `...` spread at a call site does the reverse — expanding an existing array back into individual arguments." },
      { kind: "code", code: "fn total(...xs: int) -> int:\n  s = 0\n  for x of xs:\n    s = s + x\n  return s\n\nprint(total(1, 2, 3, 4))\nnums = [3, 1, 2]\nprint(Math.max(...nums))" },
      { kind: "text", text: "Arrow functions are compact, expression-bodied functions — a natural fit for the callbacks that `map`, `filter`, and `reduce` expect. They close over the variables in scope where they are written, capturing them by reference; reach for a named `fn` when the body needs more than a single expression." },
      { kind: "code", code: "fn adder(n: int):\n  return x => x + n\n\nadd5 = adder(5)\nprint(add5(10))" },
      { kind: "text", text: "A function can call itself, which is often the most direct way to express a problem defined in terms of smaller versions of itself — each call peels off a layer until it reaches a base case." },
      { kind: "code", code: "fn fib(n: int) -> int:\n  if n < 2:\n    return n\n  return fib(n - 1) + fib(n - 2)\n\nprint(fib(10))" },
      { kind: "note", text: "Functions that use `await` are `async`, and `fn*` declares a generator — both are covered in Async & generators." },
    ],
  },
  {
    id: "arrays",
    title: "Arrays",
    group: "Language",
    summary: "Building, transforming, and searching ordered collections.",
    blocks: [
      { kind: "text", text: "Arrays are ordered, zero-indexed collections that grow and shrink in place. `push` and `pop` add and remove at the end, `unshift` and `shift` do the same at the front, and `length` reports how many elements there are." },
      { kind: "code", code: "xs = [1, 2]\nxs.push(3)\nprint(xs, xs.length)" },
      { kind: "heading", text: "Transforming" },
      { kind: "text", text: "The transforming methods each take a function and return a new array rather than changing the original: `map` rewrites every element, `filter` keeps the ones a test accepts, and `reduce` folds them all into a single value. `for_each` is the exception — it returns nothing and exists only to run a function for its side effects." },
      { kind: "code", code: "nums = [1, 2, 3, 4]\nprint(nums.filter(n => n % 2 == 0).map(n => n * 10))\nprint(nums.reduce((acc, n) => acc + n, 0))\nprint(nums.flat_map(n => [n, n * 10]))" },
      { kind: "heading", text: "Searching" },
      { kind: "text", text: "One family of methods locates an element:" },
      { kind: "list", items: [
        "`find(fn)` — the first element that passes a test.",
        "`find_index(fn)` — the position of that element.",
        "`includes(value)` — whether a value is present.",
        "`index_of(value)` — the position of a value, or `-1`.",
      ] },
      { kind: "code", code: "print([1, 2, 3, 4].find(n => n > 2))\nprint([10, 20, 30].index_of(20))\nprint([1, 2, 3].includes(2))" },
      { kind: "heading", text: "Rearranging" },
      { kind: "text", text: "Another family reshapes an array:" },
      { kind: "list", items: [
        "`sort()` — order the elements.",
        "`reverse()` — flip the order.",
        "`slice(start, end)` — copy the range `[start, end)`.",
        "`concat(other)` — join two arrays end to end.",
        "`join(sep)` — render the elements into a string.",
      ] },
      { kind: "code", code: "print([3, 1, 2].sort())\nprint([1, 2, 3].reverse())\nprint([1, 2, 3, 4].slice(1, 3))\nprint([1, 2].concat([3, 4]))\nprint([1, 2, 3].join(\"-\"))" },
      { kind: "text", text: "The spread operator `...` copies an array's elements into a new array literal — an easy way to build an extended or combined array without touching the original." },
      { kind: "code", code: "xs = [1, 2]\nprint([...xs, 3, 4])" },
    ],
  },
  {
    id: "objects-maps-sets",
    title: "Objects, Maps & Sets",
    group: "Language",
    summary: "Object literals, spread, and the Map and Set collections.",
    blocks: [
      { kind: "text", text: "Object literals map string keys to values of any type. Read a field with dot access, and use spread inside a new literal to copy an object with some fields changed — the original is left untouched." },
      { kind: "code", code: "user = { name: \"Ada\", score: 10 }\nprint(user.name, user.score)\nprint({ ...user, score: 20 })" },
      { kind: "text", text: "`Object.keys`, `Object.values`, and `Object.entries` turn an object's own fields into arrays — of the keys, the values, or `[key, value]` pairs respectively — so you can iterate or transform them like any other array." },
      { kind: "code", code: "print(Object.keys({ a: 1, b: 2 }))\nprint(Object.values({ a: 1, b: 2 }))\nprint(Object.entries({ a: 1 }))" },
      { kind: "heading", text: "Map" },
      { kind: "text", text: "A `Map` is a keyed collection like an object, but its keys can be values of any type and it remembers the order they were inserted:" },
      { kind: "list", items: [
        "`set(key, value)` / `get(key)` — write and read an entry.",
        "`has(key)` — test whether a key is present.",
        "`keys()` / `values()` — iterate the keys or the values.",
        "`size` — how many entries it holds.",
      ] },
      { kind: "code", code: "m = Map()\nm.set(\"a\", 1)\nm.set(\"b\", 2)\nprint(m.get(\"a\"), m.size)\nfor k of m.keys():\n  print(k)" },
      { kind: "heading", text: "Set" },
      { kind: "text", text: "A `Set` stores a collection of unique values — adding one that is already present is a no-op, which makes a Set the natural tool for deduplicating or membership testing. `add` inserts a value, `has` tests for one, and `size` counts them." },
      { kind: "code", code: "s = Set()\ns.add(1)\ns.add(1)\nprint(s.size, s.has(1))" },
    ],
  },
  {
    id: "classes",
    title: "Classes & interfaces",
    group: "Language",
    summary: "Fields, accessors, statics, inheritance, and structural types.",
    blocks: [
      { kind: "text", text: "A `class` bundles data together with the behavior that acts on it. Every member declares its visibility — `public`, `private`, or `protected` — so the class's surface is explicit, and the `constructor` runs when an instance is built to set up `this`. Construct one by calling the class like a function; the `new` keyword is optional." },
      { kind: "code", code: "class Account:\n  public constructor(owner: string, balance: float = 0.0):\n    this.owner = owner\n    this.balance = balance\n  public deposit(amount: float) -> Account:\n    this.balance += amount\n    return this\n\nacc = Account(\"alice\")\nprint(acc.deposit(100.0).balance)" },
      { kind: "heading", text: "Getters & setters" },
      { kind: "text", text: "A `get` accessor exposes a computed value that reads like a plain property instead of a method call, and a matching `set` accessor runs when that property is assigned — the place to keep a derived value in sync or to validate an incoming one." },
      { kind: "code", code: "class Temperature:\n  public constructor(celsius: float):\n    this.c = celsius\n  public get fahrenheit():\n    return this.c * 9.0 / 5.0 + 32.0\n  public set fahrenheit(f):\n    this.c = (f - 32.0) * 5.0 / 9.0\n\nt = Temperature(25.0)\nprint(t.fahrenheit)\nt.fahrenheit = 212.0\nprint(t.c)" },
      { kind: "heading", text: "Static members" },
      { kind: "text", text: "A `static` member belongs to the class itself rather than to any one instance, so it is shared across all of them. That makes statics a good home for constants, shared state, and factory methods that build instances — even from inside a `private` constructor." },
      { kind: "code", code: "class Config:\n  private static instance = Config(\"prod\")\n  private constructor(env):\n    this.env = env\n  public static get_instance():\n    return Config.instance\n  public describe() -> string:\n    return \"config:\" + this.env\n\na = Config.get_instance()\nb = Config.get_instance()\nprint(a.describe(), a === b)" },
      { kind: "heading", text: "Inheritance & abstract classes" },
      { kind: "text", text: "`extends` makes one class inherit the fields and methods of another, and `super` calls up to the parent's constructor or methods. An `abstract` class serves as a base that cannot be constructed on its own; it may declare `abstract` methods with no body, which every concrete subclass is then required to implement." },
      { kind: "code", code: "class Shape:\n  public constructor(name: string):\n    this.name = name\n  public area() -> float:\n    return 0.0\n\nclass Circle extends Shape:\n  public constructor(r: float):\n    super(name=\"circle\")\n    this.r = r\n  public area() -> float:\n    return 3.14159 * this.r * this.r\n\nprint(Circle(2.0).area())" },
      { kind: "code", code: "abstract class LoggerApp:\n  public abstract make() -> string\n  public run() -> string:\n    return this.make()\n\nclass TextApp extends LoggerApp:\n  public make() -> string:\n    return \"text\"\n\nprint(TextApp().run())" },
      { kind: "heading", text: "Interfaces & type aliases" },
      { kind: "text", text: "An `interface` describes the shape an object must have, `type` gives a reusable name to any type, and a trailing `?` on a field marks it optional. Typing in Tera is structural — any value with the right fields satisfies an interface, whether or not it was declared to — and a class can add `implements` to have the checker verify it against one." },
      { kind: "code", code: "type UserId = int | string\n\ninterface User:\n  id: UserId\n  name: string\n  active?: bool\n\nada: User = { id: 1, name: \"Ada\" }\nprint(ada.name)" },
      { kind: "code", code: "interface Logger:\n  log(message: string) -> string\n\nclass TextLogger implements Logger:\n  public log(message: string) -> string:\n    return \"log: \" + message\n\nprint(TextLogger().log(\"hi\"))" },
    ],
  },
  {
    id: "async",
    title: "Async & generators",
    group: "Language",
    summary: "async functions, await, promises, and generators.",
    blocks: [
      { kind: "text", text: "A function that awaits anything is asynchronous and must be marked `async fn`. Inside it, `await` suspends the function until a promise settles and then hands back the resolved value — letting you write code that waits for results in a straight line instead of a nest of callbacks." },
      { kind: "code", code: "async fn fetch_user(id: int):\n  return { id: id, name: `user-${id}` }\n\nasync fn greet(id: int) -> string:\n  user = await fetch_user(id)\n  return \"hello \" + user.name\n\nasync fn main() -> void:\n  print(await greet(7))\n\nmain()" },
      { kind: "text", text: "A rejected promise surfaces at the `await` as a thrown error, propagating exactly like any other `throw`. That means the ordinary `try`/`catch` handles asynchronous failures with no special syntax." },
      { kind: "code", code: "async fn safe(a: float, b: float) -> float:\n  if b == 0.0:\n    throw \"div by zero\"\n  return a / b\n\nasync fn run() -> void:\n  try:\n    print(await safe(10.0, 2.0))\n    print(await safe(1.0, 0.0))\n  catch e:\n    print(\"caught:\", e)\n\nrun()" },
      { kind: "heading", text: "Promises" },
      { kind: "text", text: "A promise is a placeholder for a value that will arrive later. It lives in one of three states — pending until it settles, then either fulfilled with a value or rejected with an error. `Promise.resolve` and `Promise.reject` build ones that are already settled, while the `Promise((resolve, reject) => ...)` constructor wraps a computation that settles by calling one of the two functions it is handed." },
      { kind: "code", code: "p = Promise((resolve, reject) => resolve(42))\np.then(v => print(\"got\", v))" },
      { kind: "text", text: "`then` runs a callback on the fulfilled value and returns a new promise, so transformations chain. `catch` handles a rejection from anywhere earlier in the chain, and `finally` runs a callback once the promise settles either way — the place for cleanup that must run regardless of outcome." },
      { kind: "code", code: "Promise.resolve(10).then(v => v * 2).then(v => v + 1).then(v => print(v))" },
      { kind: "code", code: "Promise.reject(\"boom\").catch(e => print(\"caught\", e))" },
      { kind: "code", code: "Promise.resolve(1).finally(() => print(\"cleanup\")).then(v => print(\"value\", v))" },
      { kind: "text", text: "Four combinators wait on a whole array of promises at once. `Promise.all` fulfills with all their values, or rejects the moment any one does; `Promise.race` settles with the first to finish, win or lose; `Promise.allSettled` waits for every one and never rejects, reporting each as `{ status, value }` or `{ status, reason }`; and `Promise.any` fulfills with the first success, ignoring rejections unless they all fail." },
      { kind: "code", code: "async fn go() -> void:\n  rs = await Promise.all([Promise.resolve(1), Promise.resolve(2)])\n  print(rs)\n\ngo()" },
      { kind: "code", code: "async fn go() -> void:\n  print(await Promise.race([Promise.resolve(\"first\"), Promise.resolve(\"second\")]))\n\ngo()" },
      { kind: "code", code: "async fn go() -> void:\n  rs = await Promise.allSettled([Promise.resolve(1), Promise.reject(\"bad\")])\n  print(rs)\n\ngo()" },
      { kind: "code", code: "async fn go() -> void:\n  print(await Promise.any([Promise.reject(\"x\"), Promise.resolve(\"won\")]))\n\ngo()" },
      { kind: "heading", text: "Generators" },
      { kind: "text", text: "`fn*` declares a generator — a function that produces a sequence of values lazily. Each `yield` emits one value and pauses until the next is asked for, and a `for … of` loop drives the generator, pulling values until it finishes." },
      { kind: "code", code: "fn* gen():\n  yield 1\n  yield 2\n  yield 3\n\nfor v of gen():\n  print(v)" },
    ],
  },
  {
    id: "namespaces",
    title: "Built-in namespaces",
    group: "Language",
    summary: "Math and JSON helpers.",
    blocks: [
      { kind: "text", text: "The `Math` namespace collects the standard numeric helpers and constants:" },
      { kind: "list", items: [
        "`abs`, `floor`, `ceil`, `round` — sign and rounding.",
        "`pow`, `sqrt` — powers and roots.",
        "`min`, `max` — the smallest / largest of several values.",
        "`Math.PI`, `Math.E` — mathematical constants.",
      ] },
      { kind: "code", code: "print(Math.abs(-5), Math.floor(2.7), Math.ceil(2.1), Math.round(2.5))\nprint(Math.pow(2, 10), Math.sqrt(81), Math.min(3, 1, 2), Math.max(3, 1, 2))\nprint(Math.PI, Math.E)" },
      { kind: "text", text: "`Math.random` returns a fresh `float` in the half-open range `[0, 1)`. Scale and shift it to draw from any range you need — multiplying, flooring, and offsetting turns it into dice rolls, random indices, or samples." },
      { kind: "code", code: "roll = Math.floor(Math.random() * 6) + 1\nprint(roll >= 1 and roll <= 6)" },
      { kind: "text", text: "`JSON.stringify` serializes a value into its JSON text, and `JSON.parse` reads that text back into a value — the round trip used to store data or exchange it with the world outside the program." },
      { kind: "code", code: "text = JSON.stringify({ a: 1, b: [2, 3] })\nprint(text)\nprint(JSON.parse(text).a)" },
    ],
  },
  {
    id: "tensors",
    title: "Tensors",
    group: "Extensions",
    summary: "N-dimensional arrays, shapes, math, reductions, and gradients.",
    blocks: [
      { kind: "text", text: "Tensors are n-dimensional numeric arrays — the type the whole numerical and machine-learning side of Tera is built on. Models, gradients, and DataFrame exports all speak in tensors." },
      { kind: "heading", text: "Creating tensors" },
      { kind: "text", text: "Build a tensor from a literal or nested arrays, or reach for a factory to fill or generate a shape:" },
      { kind: "list", items: [
        "`tensor(data)` — from a scalar, an array, or nested arrays.",
        "`zeros(shape)` / `ones(shape)` — a shape filled with `0` or `1`.",
        "`full(shape, value)` — a shape filled with one constant.",
        "`eye(n)` — an `n × n` identity matrix.",
        "`arange(start, end)` — the integers in the half-open range `[start, end)`.",
        "`linspace(start, end, n)` — `n` evenly spaced values, both endpoints included.",
        "`randn(shape)` — samples drawn from the standard normal distribution.",
        "`randperm(n)` — a random permutation of `0 … n-1`.",
      ] },
      { kind: "code", code: "a = tensor([[1, 2], [3, 4]])\nprint(a.shape)\nprint(zeros([2, 2]).shape, ones([3]).shape, eye(2).shape)" },
      { kind: "code", code: "print(full([2, 2], 7).to_array())\nprint(linspace(0.0, 1.0, 5).to_array())\nprint(randn([2, 3]).shape)" },
      { kind: "text", text: "Going the other way, `to_array` reads a tensor back into nested arrays, and `item` extracts the single scalar from a one-element tensor." },
      { kind: "code", code: "print(tensor([[1.0, 2.0], [3.0, 4.0]]).to_array())\nprint(tensor([42.0]).item())" },
      { kind: "heading", text: "Inspecting a tensor" },
      { kind: "text", text: "Every tensor exposes read-only properties describing its size, element type, and memory layout:" },
      { kind: "list", items: [
        "`shape` — the size along each axis.",
        "`ndim` (also `rank`) — how many axes it has.",
        "`numel` — the total number of elements.",
        "`dtype` — the element type, `f32` by default.",
        "`device` — where it lives, `cpu` unless moved.",
        "`strides` / `is_contiguous` — how it is laid out in memory.",
      ] },
      { kind: "code", code: "a = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])\nprint(a.shape, a.ndim, a.numel)\nprint(a.dtype, a.device, a.is_contiguous)" },
      { kind: "heading", text: "Shape & layout" },
      { kind: "text", text: "These reshape a tensor's axes, mostly by changing how the data is viewed rather than copying it:" },
      { kind: "list", items: [
        "`reshape(shape)` — reinterpret the same elements under a new shape.",
        "`transpose(a, b)` — swap two axes.",
        "`permute(order)` — reorder every axis at once.",
        "`unsqueeze(dim)` — insert a length-1 axis; `squeeze(dim)` removes one.",
        "`expand(shape)` — stretch a length-1 axis to a larger size without copying.",
        "`narrow(dim, start, length)` / `select(dim, index)` / `slice` — cut out a sub-region.",
        "`contiguous` — materialize a compact copy of a view; `clone` copies a tensor outright.",
      ] },
      { kind: "code", code: "print(arange(0, 6).reshape([2, 3]).shape)\nprint(tensor([[1, 2, 3], [4, 5, 6]]).transpose(0, 1).shape)\nprint(zeros([2, 3, 4]).permute([2, 0, 1]).shape)" },
      { kind: "code", code: "print(tensor([1.0, 2.0]).unsqueeze(0).shape)\nprint(zeros([1, 3]).squeeze(0).shape)" },
      { kind: "code", code: "print(ones([1, 3]).expand([2, 3]).shape)\nprint(arange(0, 6).narrow(0, 1, 3).to_array())\nprint(tensor([[1.0, 2.0], [3.0, 4.0]]).select(0, 1).to_array())" },
      { kind: "heading", text: "Elementwise arithmetic" },
      { kind: "text", text: "Arithmetic runs elementwise, and a scalar broadcasts across the whole tensor. Each operator has a method form that reads well in a chain:" },
      { kind: "list", items: [
        "`+` `-` `*` `/` — or the methods `add`, `sub`, `mul`, `div`.",
        "`pow(exp)` — raise every element to a power.",
        "`remainder(other)` — the elementwise modulo.",
        "`maximum(other)` / `minimum(other)` — the elementwise larger / smaller of two tensors.",
        "`@` (or `matmul`) — the matrix product; `dot` — the vector inner product.",
      ] },
      { kind: "code", code: "print((tensor([1.0, 2.0]) + 10.0).to_array())\nprint(tensor([1.0, 2.0, 3.0]).pow(2.0).to_array())" },
      { kind: "code", code: "a = tensor([1.0, 2.0, 3.0])\nb = tensor([4.0, 5.0, 6.0])\nprint(a.add(b).to_array(), a.mul(b).to_array())\nprint(a.maximum(tensor([2.0, 1.0, 5.0])).to_array())\nprint(a.dot(b).item())" },
      { kind: "code", code: "a = tensor([[1.0, 2.0], [3.0, 4.0]])\nb = eye(2)\nprint((a @ b).to_array())" },
      { kind: "heading", text: "Unary functions" },
      { kind: "text", text: "A family of one-argument functions maps over every element:" },
      { kind: "list", items: [
        "`neg`, `abs`, `sign` — sign manipulation.",
        "`exp`, `log`, `sqrt`, `rsqrt` — exponentials and roots.",
        "`sin`, `cos`, `tanh` — trigonometric.",
        "`floor`, `ceil` — rounding down and up.",
        "`relu`, `sigmoid`, `gelu`, `silu`, `softmax` — neural-network activations.",
      ] },
      { kind: "code", code: "print(tensor([-2.0]).abs().item(), tensor([2.0]).neg().item())\nprint(tensor([1.0, 4.0, 9.0]).sqrt().to_array())\nprint(tensor([-3.0, 0.0, 2.0]).sign().to_array())\nprint(tensor([2.7, -2.7]).floor().to_array())" },
      { kind: "code", code: "print(tensor([-1.0, 2.0, -3.0]).relu().to_array())\nprint(tensor([0.0]).sigmoid().item(), tensor([0.0]).tanh().item())\nprint(tensor([1.0, 2.0, 3.0]).softmax(-1).to_array())" },
      { kind: "heading", text: "Comparisons" },
      { kind: "text", text: "The comparison methods test two tensors elementwise and return a mask of `1`s and `0`s:" },
      { kind: "list", items: [
        "`eq` / `ne` — equal / not equal.",
        "`lt` / `le` — less than / less-or-equal.",
        "`gt` / `ge` — greater than / greater-or-equal.",
      ] },
      { kind: "code", code: "a = tensor([1.0, 2.0, 3.0])\nprint(a.lt(tensor([2.0, 2.0, 2.0])).to_array())\nprint(a.eq(tensor([1.0, 0.0, 3.0])).to_array())" },
      { kind: "heading", text: "Reductions" },
      { kind: "text", text: "Reductions collapse a tensor down to a summary. Pass an axis to reduce just that dimension, and a further `true` to keep it as a length-1 axis:" },
      { kind: "list", items: [
        "`sum`, `mean`, `prod` — combine all the elements into one.",
        "`max`, `min` — the largest / smallest value.",
        "`argmax`, `argmin` — the index of the largest / smallest.",
        "`softmax`, `log_softmax` — normalize along an axis.",
      ] },
      { kind: "code", code: "print(tensor([1.0, 2.0, 3.0, 4.0]).mean().item())\nprint(tensor([1.0, 5.0, 3.0]).max().item(), tensor([1.0, 5.0, 3.0]).argmax().item())" },
      { kind: "code", code: "print(tensor([1.0, 2.0, 3.0, 4.0]).prod().item())\nprint(tensor([3.0, 1.0, 2.0]).min().item(), tensor([3.0, 1.0, 2.0]).argmin().item())\nprint(tensor([[1.0, 2.0], [3.0, 4.0]]).sum(0).to_array())" },
      { kind: "heading", text: "Combining tensors" },
      { kind: "text", text: "Where the shape operations cut a tensor apart, these build tensors up:" },
      { kind: "list", items: [
        "`cat(tensors, axis)` — concatenate along an existing axis.",
        "`stack(tensors)` — join tensors along a brand-new axis.",
        "`where(mask, a, b)` — choose elementwise between two tensors by a boolean mask.",
      ] },
      { kind: "code", code: "print(cat([tensor([1.0]), tensor([2.0])]).to_array())\nprint(stack([tensor([1.0]), tensor([2.0])]).shape)\nprint(where(tensor([true, false]), tensor([1.0, 1.0]), tensor([9.0, 9.0])).to_array())" },
      { kind: "heading", text: "Automatic gradients" },
      { kind: "text", text: "Automatic differentiation is what makes training possible — Tera records the operations on a tracked tensor and replays them in reverse to get derivatives:" },
      { kind: "list", items: [
        "`grad=true` — build a tensor that records every operation applied to it onto a graph.",
        "`is_leaf` — whether the tensor is a leaf of that graph (an input, not a computed result).",
        "`backward` — from a scalar result, walk the graph in reverse to fill each leaf's gradient.",
        "`grad` — the derivative `backward` accumulated for this tensor.",
        "`detach` — a copy cut out of the graph: a value without its history.",
      ] },
      { kind: "code", code: "x = tensor([1.0, 2.0, 3.0], grad=true)\ny = (x * x).sum()\ny.backward()\nprint(x.grad.to_array())" },
      { kind: "code", code: "x = tensor([1.0, 2.0], grad=true)\nprint(x.is_leaf)\nprint(x.detach().to_array())" },
    ],
  },
  {
    id: "models",
    title: "Models & neural networks",
    group: "Extensions",
    summary: "Layers, forward passes, optimizers, and training.",
    wip: true,
    blocks: [],
  },
  {
    id: "dataframes",
    title: "DataFrames",
    group: "Extensions",
    summary: "Columnar tables with a lazy, composable query API.",
    blocks: [
      { kind: "text", text: "A `DataFrame` is a table stored one column at a time rather than one row at a time. That columnar layout is what makes analytical work fast: filtering, grouping, and aggregating sweep down whole columns of like-typed values at once, the way the query engine underneath is built to run them. Create a frame by passing each column as a named array — the column types are inferred from the values — and call `show` to print it as a table." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[10, 20, 30])\ndf.show()" },
      { kind: "text", text: "Every DataFrame is lazy. A transformation like `select` or `filter` does not touch any data; it records one more step in a query plan and hands back a new frame. Nothing actually runs until you materialize the result — with `show`, `collect`, `count`, or `to_tensor` — at which point the whole plan executes as a single query. `columns` reads the column names straight off the plan without running it." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\"], value=[10, 20])\nprint(df.columns())" },
      { kind: "heading", text: "Selecting & filtering" },
      { kind: "text", text: "Picture a query as trimming a table along two axes: `select` chooses which columns survive, and `filter` chooses which rows do. A row filter is written as a column expression — `col(\"value\")` stands for that column's value in each row, and methods like `gt`, `lt`, and `eq` turn it into a per-row boolean that `filter` tests." },
      { kind: "code", code: "df = DataFrame(a=[1, 2], b=[3, 4], c=[5, 6])\ndf.select(\"a\", \"c\").show()" },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[10, 20, 30])\ndf.filter(col(\"value\").gt(10)).show()" },
      { kind: "text", text: "Column expressions carry the full comparison set — `eq`, `ne`, `lt`, `le`, `gt`, `ge` — plus `between`, `isin`, and `like` for string patterns. Combine them with `and`/`or`, negate with `not`, and `where` reads as a synonym for `filter`." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\", \"D\"], value=[5, 15, 25, 35])\ndf.where(col(\"value\").between(10, 30)).show()" },
      { kind: "code", code: "df = DataFrame(region=[\"N\", \"S\", \"E\", \"W\"], value=[1, 2, 3, 4])\ndf.filter(col(\"region\").isin(\"N\", \"E\")).show()" },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[10, 20, 30], ok=[true, false, true])\ndf.filter(col(\"value\").gt(10).and(col(\"ok\").eq(true))).show()" },
      { kind: "code", code: "df = DataFrame(name=[\"Ada\", \"Bob\", \"Alan\"], team=[\"x\", \"y\", \"z\"])\ndf.filter(col(\"name\").like(\"A%\")).show()" },
      { kind: "text", text: "`drop` removes columns by name — the complement of `select`." },
      { kind: "code", code: "df = DataFrame(a=[1, 2], b=[3, 4], c=[5, 6])\ndf.drop(\"b\").show()" },
      { kind: "heading", text: "Derived columns" },
      { kind: "text", text: "`with_column` returns a new frame with one extra column, computed for every row from a column expression. Arithmetic reads as a chain of methods — `add`, `sub`, `mul`, `div` — and `alias` (or `as`) names the result. Passing the name of a column that already exists replaces it rather than adding a duplicate." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\"], value=[10, 20])\ndf.with_column(\"double\", col(\"value\").mul(2)).show()" },
      { kind: "text", text: "`expr` parses a scalar SQL string against the frame's columns — handy when an arithmetic expression reads more clearly written out." },
      { kind: "code", code: "df = DataFrame(price=[10.0, 20.0], qty=[3, 2])\ndf.with_column(\"total\", expr(\"price * qty\")).show()" },
      { kind: "text", text: "`cast` converts a column to another type — `\"int\"`, `\"float\"`, `\"string\"`, or `\"bool\"`." },
      { kind: "code", code: "df = DataFrame(price=[10.9, 20.2, 30.7])\ndf.with_column(\"whole\", col(\"price\").cast(\"int\")).show()" },
      { kind: "heading", text: "Grouping & aggregation" },
      { kind: "text", text: "`group_by` partitions the rows by one or more key columns, and `agg` collapses each partition into a single output row. `sum`, `avg`, `min`, `max`, and `count` are the built-in aggregates; give each one an `alias` so the resulting column carries a clear name. The output has one row per distinct group." },
      { kind: "code", code: "df = DataFrame(group=[\"a\", \"a\", \"b\"], value=[1, 2, 3])\ndf.group_by(\"group\").agg(sum(col(\"value\")).alias(\"total\")).show()" },
      { kind: "code", code: "df = DataFrame(g=[\"a\", \"a\", \"b\"], v=[1, 2, 3])\ndf.group_by(\"g\").agg(sum(col(\"v\")).alias(\"sum\"), avg(col(\"v\")).alias(\"avg\")).show()" },
      { kind: "text", text: "Aggregates also accept a column name directly, and `count_star()` counts the rows in each group." },
      { kind: "code", code: "df = DataFrame(region=[\"N\", \"N\", \"S\"], qty=[5, 3, 8])\ndf.group_by(\"region\").agg(count_star().alias(\"orders\"), sum(\"qty\").alias(\"total_qty\")).order_by(\"region\").show()" },
      { kind: "heading", text: "Joining tables" },
      { kind: "text", text: "`join` matches rows from two DataFrames on a shared column. It is an inner join by default; pass a join type — `\"LEFT\"`, `\"RIGHT\"`, or `\"FULL\"` — as the third argument to keep unmatched rows, filling the gaps with `null`." },
      { kind: "code", code: "left = DataFrame(region=[\"N\", \"S\"], revenue=[100, 200])\nright = DataFrame(region=[\"N\", \"S\"], manager=[\"An\", \"Binh\"])\nleft.join(right, \"region\").show()" },
      { kind: "code", code: "a = DataFrame(id=[1, 2, 3], value=[10, 20, 30])\nb = DataFrame(id=[1, 2], note=[\"x\", \"y\"])\na.join(b, \"id\", \"LEFT\").order_by(\"id\").show()" },
      { kind: "text", text: "`is_null` and `is_not_null` test a column for missing values — the natural way to keep or drop the unmatched rows a left join leaves behind." },
      { kind: "code", code: "a = DataFrame(id=[1, 2, 3], value=[10, 20, 30])\nb = DataFrame(id=[1, 2], note=[\"x\", \"y\"])\na.join(b, \"id\", \"LEFT\").filter(col(\"note\").is_null()).show()" },
      { kind: "heading", text: "Combining rows" },
      { kind: "text", text: "`union` and `union_all` stack two DataFrames that share their columns; both keep duplicates, so reach for `distinct` when you want a set." },
      { kind: "code", code: "a = DataFrame(x=[1, 2])\nb = DataFrame(x=[2, 3])\na.union(b).distinct().order_by(\"x\").show()" },
      { kind: "code", code: "a = DataFrame(x=[1, 2])\nb = DataFrame(x=[2, 3])\na.union_all(b).order_by(\"x\").show()" },
      { kind: "heading", text: "Ordering & slicing" },
      { kind: "text", text: "`order_by` sorts the rows by one or more columns, `limit` and `head` keep a prefix of them, and `distinct` drops exact duplicate rows. Sorting comes before slicing in the plan, so `order_by` followed by `limit` gives you the top rows by that key." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[30, 10, 20])\ndf.order_by(\"value\").show()" },
      { kind: "text", text: "`col(\"name\").desc()` sorts a column in descending order; `asc()` is the explicit ascending form." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[10, 30, 20])\ndf.order_by(col(\"value\").desc()).show()" },
      { kind: "code", code: "df = DataFrame(x=[1, 1, 2, 2, 3])\ndf.limit(2).show()\ndf.distinct().show()" },
      { kind: "text", text: "Because each step only extends the plan, a whole pipeline of `filter`, `with_column`, and `order_by` fuses into one query that runs a single time at the end — the engine is free to reorder and combine the steps for you. `explain` prints that plan so you can see the shape of the work before paying to run it." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[10, 20, 30])\ndf.filter(col(\"value\").gt(10)).with_column(\"double\", col(\"value\").mul(2)).order_by(\"value\").show()" },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[10, 20, 30])\nplan = df.filter(col(\"value\").gt(10)).with_column(\"double\", col(\"value\").mul(2))\nprint(plan.explain())" },
      { kind: "heading", text: "Pulling results" },
      { kind: "text", text: "Materializing a frame is where the query finally runs, and because that work is asynchronous the terminal operations return promises you `await`: `count` for the number of rows, `collect` for the rows themselves as objects, and `to_tensor` to pack the numeric columns into a tensor — the bridge from a table of data to the models in the previous chapters." },
      { kind: "code", code: "async fn summary() -> void:\n  df = DataFrame(a=[1, 2, 3], b=[4.0, 5.0, 6.0])\n  print(await df.count())\n  rows = await df.collect()\n  print(rows)\n\nsummary()" },
      { kind: "code", code: "async fn to_matrix() -> void:\n  df = DataFrame(a=[1.0, 2.0], b=[3.0, 4.0])\n  t = await df.to_tensor()\n  print(t.shape)\n\nto_matrix()" },
      { kind: "text", text: "`to_tensor` rejects non-numeric columns, so `encode` turns a categorical column into integer ids first — it returns the encoded tensor together with the list of classes those ids index into." },
      { kind: "code", code: "async fn encode_city() -> void:\n  df = DataFrame(city=[\"NY\", \"LA\", \"NY\"], value=[1, 2, 3])\n  [codes, classes] = await df.encode(\"city\")\n  print(codes.to_array())\n  print(classes)\n\nencode_city()" },
      { kind: "note", text: "`load_csv(path)` reads a CSV file into a DataFrame, parsing numeric fields automatically — the entry point for analysing data that lives on disk rather than in literals." },
    ],
  },
  {
    id: "charts",
    title: "Charts",
    group: "Extensions",
    summary: "Turning data into inline visualizations.",
    wip: true,
    blocks: [],
  },
  {
    id: "quant",
    title: "Quant & finance",
    group: "Extensions",
    summary: "Backtesting, signals, portfolios, and risk metrics.",
    wip: true,
    blocks: [],
  },
  {
    id: "reactivity",
    title: "Reactivity",
    group: "Extensions",
    summary: "Signals, computed values, effects, and batching.",
    blocks: [
      { kind: "text", text: "Reactivity lets values that change over time drive the code that depends on them, without you wiring the updates by hand. The primitives are part of the language: you declare them with keywords and read them by name, and the runtime tracks who depends on whom and re-runs only what needs re-running." },
      { kind: "heading", text: "Signals & computed" },
      { kind: "text", text: "Two building blocks hold and derive reactive state:" },
      { kind: "list", items: [
        "`signal name = value` — writable state you read by name and change through its methods.",
        "`computed name = expr` — a value derived from the reactive reads in `expr`, which re-derives itself when any of them changes.",
      ] },
      { kind: "text", text: "A `computed` is lazy: it recomputes the next time it is read after a dependency has changed, so it never does work nobody looks at." },
      { kind: "code", code: "signal count = 2\ncomputed doubled = count * 2\nprint(doubled)\ncount.set(5)\nprint(doubled)" },
      { kind: "heading", text: "Updating a signal" },
      { kind: "text", text: "A signal is changed through a small set of methods:" },
      { kind: "list", items: [
        "`set(value)` — replace the value and notify everything that depends on it.",
        "`update(fn)` — set the next value from the current one, as `fn(current)`.",
        "`peek()` — read the current value without subscribing the surrounding reactive scope to it.",
      ] },
      { kind: "code", code: "signal n = 1\nn.update(v => v + 41)\nprint(n, n.peek())" },
      { kind: "heading", text: "Effects" },
      { kind: "text", text: "An `effect:` block runs its body once immediately, tracks every reactive value it reads, and re-runs whenever any of them changes — the home for side effects like logging, drawing, or syncing to the world outside." },
      { kind: "code", code: "signal name = \"Ada\"\neffect:\n  print(\"hello\", name)\nname.set(\"Grace\")" },
      { kind: "text", text: "Call `cleanup` inside an effect to register teardown for whatever that run set up; it fires just before the next re-run and when the effect is disposed." },
      { kind: "code", code: "signal on = true\neffect:\n  print(\"effect for\", on)\n  cleanup(() => print(\"cleaning up\"))\non.set(false)" },
      { kind: "heading", text: "Batching & fine control" },
      { kind: "text", text: "Three helpers control when dependents run and what gets tracked:" },
      { kind: "list", items: [
        "`batch(fn)` — group several writes so dependents recompute once, after `fn` returns.",
        "`untrack(fn)` — read reactive values inside `fn` without subscribing to them.",
        "`watch(source, fn)` — run `fn(current, previous)` whenever a signal or computed changes.",
      ] },
      { kind: "code", code: "signal a = 1\nsignal b = 2\ncomputed s = a + b\n\nfn bump():\n  a.set(10)\n  b.set(20)\n\nbatch(bump)\nprint(s)" },
      { kind: "code", code: "signal a = 1\nsignal b = 10\neffect:\n  print(\"sum\", a + untrack(() => b))\na.set(2)\nb.set(20)" },
      { kind: "code", code: "signal v = 1\nwatch(v, (cur, prev) => print(\"changed\", prev, cur))\nv.set(2)\nv.set(3)" },
      { kind: "heading", text: "Subscriptions & ownership" },
      { kind: "text", text: "To bridge reactivity to ordinary code and to control lifetimes:" },
      { kind: "list", items: [
        "`subscribe(fn)` — call `fn` on every change and return a function that unsubscribes.",
        "`dispose()` — tear a signal or computed down and detach its dependents.",
        "`root(fn)` — open an owner scope; `fn(dispose)` receives a function that disposes everything created inside it at once.",
      ] },
      { kind: "code", code: "signal n = 0\nunsub = n.subscribe(v => print(\"saw\", v))\nn.set(1)\nunsub()\nn.set(2)" },
      { kind: "heading", text: "Resources" },
      { kind: "text", text: "A `resource` wraps asynchronous data and tracks its lifecycle, so a view can react to each phase instead of juggling promises by hand:" },
      { kind: "list", items: [
        "`loading` — `true` while the request is pending or refreshing.",
        "`state` — one of `unresolved`, `pending`, `ready`, `refreshing`, or `errored`.",
        "`latest` / `error` — the last resolved value, or the last error if it failed.",
        "`refetch()` / `mutate(value)` — run the fetcher again, or set the value optimistically.",
      ] },
      { kind: "code", code: "resource user = Promise.resolve({ name: \"Ada\" })\nprint(user.loading, user.state)" },
    ],
  },
];
