export type Block =
  | { kind: "text"; text: string }
  | { kind: "heading"; text: string }
  | { kind: "code"; code: string }
  | { kind: "note"; text: string }
  | { kind: "list"; items: string[] };

export type Chapter = {
  id: string;
  title: string;
  group: string;
  summary: string;
  wip?: boolean;
  blocks: Block[];
};

export const GUIDE_CHAPTERS: Chapter[] = [
  {
    id: "introduction",
    title: "Introduction",
    group: "Language",
    summary: "What Tera is and the engine it runs on.",
    blocks: [
      { kind: "text", text: "Tera is a statically typed language for numerical and machine-learning work. Its syntax is offside — blocks open with `:` and a deeper indent, with no braces and no semicolons — and the type checker runs over your code before any of it executes. Tensors, automatic differentiation, models, DataFrames, reactive state, and charts are part of the language, not packages you import." },
      { kind: "text", text: "Tera runs on its own engine. Source is type-checked, lowered to register bytecode, and executed by a virtual machine that tiers up as code gets hot: the interpreter runs first, a baseline compiler takes over next, and a speculative optimizer compiles the hottest functions to WebAssembly. Long-running loops are swapped to optimized code mid-run through on-stack replacement, speculation that turns out wrong is deoptimized back to the interpreter, and inline caches and a generational garbage collector keep everyday code fast." },
      { kind: "code", code: "fn greet(name: string) -> string:\n  return \"Hello, \" + name\n\nprint(greet(\"Tera\"))" },
      { kind: "list", items: [
        "**Checked before it runs** — the type checker reports mistakes ahead of execution, not partway through a computation.",
        "**Offside syntax** — `:` and indentation define every block; no braces, no semicolons.",
        "**Numerics built in** — `tensor`, `model`, `DataFrame`, `signal`, and `chart` are part of the language.",
        "**Tiering JIT to WebAssembly** — hot functions are compiled and hot loops are replaced in place while they run.",
      ] },
      { kind: "note", text: "Every code block in these docs is real Tera. Copy one into a notebook cell and run it." },
    ],
  },
  {
    id: "values-and-types",
    title: "Values & types",
    group: "Language",
    summary: "Primitives, the int/float split, numbers, and strings.",
    blocks: [
      { kind: "text", text: "Tera keeps `int` and `float` apart, and rounds out the primitives with `string`, `bool`, `null`, and `undefined`. A binding takes the type of its value; annotate it with `name: Type = value` when you want it spelled out." },
      { kind: "code", code: "quantity: int = 3\nratio: float = 0.5\nname: string = \"ada\"\nready: bool = true\nprint(quantity, ratio, name, ready)" },
      { kind: "text", text: "`typeof` reports a value's runtime kind." },
      { kind: "code", code: "print(typeof 5, typeof \"s\", typeof true)" },
      { kind: "heading", text: "Numbers" },
      { kind: "text", text: "`3` is an `int` and `3.0` is a `float`; the two are distinct types. Numbers carry formatting helpers such as `to_fixed`." },
      { kind: "code", code: "print(7 / 2, 7 % 2, 2 ** 8)\nprint((3.14159).to_fixed(2))" },
      { kind: "heading", text: "Strings" },
      { kind: "text", text: "Backtick templates interpolate expressions with `${...}`." },
      { kind: "code", code: "owner = \"Ada\"\nbalance = 120\nprint(`${owner} has ${balance}`)" },
      { kind: "text", text: "Strings carry the methods you would expect — all `snake_case`." },
      { kind: "code", code: "print(\"ada\".to_upper_case())\nprint(\"HELLO\".to_lower_case())\nprint(\"  hi  \".trim())\nprint(\"hello\".slice(1, 3))" },
      { kind: "code", code: "print(\"hello\".includes(\"ell\"))\nprint(\"hello\".starts_with(\"he\"))\nprint(\"a-b-c\".replace_all(\"-\", \"+\"))\nprint(\"ab\".repeat(3))" },
      { kind: "note", text: "Passing an `int` where a `float` is wanted is fine; the other direction is a checker error." },
    ],
  },
  {
    id: "variables",
    title: "Variables & bindings",
    group: "Language",
    summary: "Introducing, updating, and destructuring values.",
    blocks: [
      { kind: "text", text: "Writing `name = value` introduces a binding — no keyword required. The type is inferred from the value, and you can annotate it with `name: Type = value` when you want it spelled out." },
      { kind: "code", code: "total = 0\npi = 3.14159\ntotal = total + pi\nprint(total)" },
      { kind: "text", text: "Assign again to update a binding. Compound operators and `++`/`--` update in place. A binding's type is fixed at its first assignment, so storing an incompatible value is a checker error." },
      { kind: "code", code: "n = 10\nn += 5\nn *= 2\nprint(n)" },
      { kind: "code", code: "i = 0\ni++\ni++\nprint(i)" },
      { kind: "text", text: "Destructuring lifts values out of arrays and objects in a single step, and nests." },
      { kind: "code", code: "[a, b] = [1, 2]\n{ name } = { name: \"Ada\", score: 10 }\nprint(a, b, name)" },
      { kind: "code", code: "{ user: { name } } = { user: { name: \"Ada\" } }\nprint(name)" },
    ],
  },
  {
    id: "operators",
    title: "Operators",
    group: "Language",
    summary: "Arithmetic, logic, null-safety, and the ternary.",
    blocks: [
      { kind: "text", text: "Arithmetic behaves as you would expect, with `**` for exponentiation and `%` for remainder." },
      { kind: "code", code: "print(7 / 2, 7 % 2, 2 ** 8)" },
      { kind: "text", text: "Boolean logic reads in words — `and`, `or`, `not` — and the symbol forms `&&`, `||`, `!` mean the same thing." },
      { kind: "code", code: "ready = true\nif ready and not false:\n  print(\"go\")" },
      { kind: "text", text: "The ternary `cond ? a : b` chooses between two values inline." },
      { kind: "code", code: "x = 7\nprint(x > 5 ? \"big\" : \"small\")" },
      { kind: "text", text: "Use `??` to fall back when a value is `null` or `undefined`, and `?.` to read through a value that might be missing without throwing." },
      { kind: "code", code: "config = { retries: null }\nprint(config.retries ?? 3)\nprint(config?.timeout)" },
      { kind: "heading", text: "Object & type operators" },
      { kind: "text", text: "`in` tests for a key, `delete` removes one, and `instanceof` checks an object's class." },
      { kind: "code", code: "o = { a: 1, b: 2 }\nprint(\"a\" in o, \"z\" in o)\ndelete o.a\nprint(o)" },
      { kind: "code", code: "class Animal:\n  public constructor():\n    this.kind = \"animal\"\n\na = Animal()\nprint(a instanceof Animal)" },
    ],
  },
  {
    id: "control-flow",
    title: "Control flow",
    group: "Language",
    summary: "Branches, loops, switch, and error handling.",
    blocks: [
      { kind: "text", text: "`if`/`else` chooses a branch. Like every block, each arm opens with `:` and an indent." },
      { kind: "code", code: "score = 82\nif score >= 90:\n  print(\"A\")\nelse:\n  print(\"needs work\")" },
      { kind: "text", text: "`for … of` walks the values of an array, string, or range; `for … in` walks keys and indices." },
      { kind: "code", code: "total = 0\nfor n of range(1, 5):\n  total = total + n\nprint(total)" },
      { kind: "code", code: "for ch of \"abc\":\n  print(ch)" },
      { kind: "code", code: "for key in { a: 1, b: 2 }:\n  print(key)" },
      { kind: "text", text: "`while` repeats while a condition holds; `break` and `continue` steer the loop." },
      { kind: "code", code: "i = 0\nwhile i < 3:\n  print(i)\n  i = i + 1" },
      { kind: "text", text: "`switch` matches a value against `case` labels. Cases fall through, so end each one with `break` unless you want the next case to run." },
      { kind: "code", code: "x = 2\nswitch x:\n  case 1:\n    print(\"one\")\n    break\n  case 2:\n    print(\"two\")\n    break\n  default:\n    print(\"other\")" },
      { kind: "text", text: "`throw` raises an error; `try`/`catch`/`finally` handles it and runs cleanup." },
      { kind: "code", code: "try:\n  throw \"boom\"\ncatch e:\n  print(\"caught\", e)\nfinally:\n  print(\"done\")" },
    ],
  },
  {
    id: "functions",
    title: "Functions",
    group: "Language",
    summary: "Declarations, defaults, rest & spread, closures, and async.",
    blocks: [
      { kind: "text", text: "Declare a function with `fn`. Annotate the parameters and the return type after `->`; locals are inferred." },
      { kind: "code", code: "fn area(width: float, height: float) -> float:\n  return width * height\n\nprint(area(3.0, 4.0))" },
      { kind: "text", text: "Parameters can carry defaults, and callers may pass any of them by name." },
      { kind: "code", code: "fn greet(name: string, greeting: string = \"Hello\") -> string:\n  return `${greeting}, ${name}`\n\nprint(greet(\"Ada\"))\nprint(greet(\"Ada\", greeting=\"Hi\"))" },
      { kind: "text", text: "A `...rest` parameter gathers extra arguments into an array, and `...` spreads an array back into a call." },
      { kind: "code", code: "fn total(...xs: int) -> int:\n  s = 0\n  for x of xs:\n    s = s + x\n  return s\n\nprint(total(1, 2, 3, 4))\nnums = [3, 1, 2]\nprint(Math.max(...nums))" },
      { kind: "text", text: "Arrow functions are compact, expression-bodied functions — a natural fit for `map`, `filter`, and `reduce`. They close over the surrounding scope; use a named `fn` when you need several statements." },
      { kind: "code", code: "fn adder(n: int):\n  return x => x + n\n\nadd5 = adder(5)\nprint(add5(10))" },
      { kind: "text", text: "Functions call themselves recursively." },
      { kind: "code", code: "fn fib(n: int) -> int:\n  if n < 2:\n    return n\n  return fib(n - 1) + fib(n - 2)\n\nprint(fib(10))" },
      { kind: "note", text: "Functions that use `await` are `async`, and `fn*` declares a generator — both are covered in Async & generators." },
    ],
  },
  {
    id: "arrays",
    title: "Arrays",
    group: "Language",
    summary: "Building, transforming, and searching ordered collections.",
    blocks: [
      { kind: "text", text: "Arrays are ordered, zero-indexed, and grow in place. `push`, `pop`, `shift`, and `unshift` add and remove at the ends; `length` reports the size." },
      { kind: "code", code: "xs = [1, 2]\nxs.push(3)\nprint(xs, xs.length)" },
      { kind: "heading", text: "Transforming" },
      { kind: "text", text: "`map`, `filter`, and `reduce` are the workhorses; `for_each` runs a function for its side effects." },
      { kind: "code", code: "nums = [1, 2, 3, 4]\nprint(nums.filter(n => n % 2 == 0).map(n => n * 10))\nprint(nums.reduce((acc, n) => acc + n, 0))\nprint(nums.flat_map(n => [n, n * 10]))" },
      { kind: "heading", text: "Searching & rearranging" },
      { kind: "text", text: "`find`, `find_index`, `includes`, and `index_of` locate elements; `sort`, `reverse`, `slice`, `concat`, and `join` reshape the array." },
      { kind: "code", code: "print([1, 2, 3, 4].find(n => n > 2))\nprint([10, 20, 30].index_of(20))\nprint([1, 2, 3].includes(2))" },
      { kind: "code", code: "print([3, 1, 2].sort())\nprint([1, 2, 3].reverse())\nprint([1, 2, 3, 4].slice(1, 3))\nprint([1, 2].concat([3, 4]))\nprint([1, 2, 3].join(\"-\"))" },
      { kind: "text", text: "The spread operator `...` copies an array's elements into a new one." },
      { kind: "code", code: "xs = [1, 2]\nprint([...xs, 3, 4])" },
    ],
  },
  {
    id: "objects-maps-sets",
    title: "Objects, Maps & Sets",
    group: "Language",
    summary: "Object literals, spread, and the Map and Set collections.",
    blocks: [
      { kind: "text", text: "Object literals map string keys to values. Read fields with dot access, and copy-with-changes using spread." },
      { kind: "code", code: "user = { name: \"Ada\", score: 10 }\nprint(user.name, user.score)\nprint({ ...user, score: 20 })" },
      { kind: "text", text: "`Object.keys`, `Object.values`, and `Object.entries` iterate an object's own fields." },
      { kind: "code", code: "print(Object.keys({ a: 1, b: 2 }))\nprint(Object.values({ a: 1, b: 2 }))\nprint(Object.entries({ a: 1 }))" },
      { kind: "heading", text: "Map" },
      { kind: "text", text: "A `Map` is a keyed collection with `set`, `get`, `has`, `keys`, `values`, and `size`." },
      { kind: "code", code: "m = Map()\nm.set(\"a\", 1)\nm.set(\"b\", 2)\nprint(m.get(\"a\"), m.size)\nfor k of m.keys():\n  print(k)" },
      { kind: "heading", text: "Set" },
      { kind: "text", text: "A `Set` holds unique values; adding a duplicate is a no-op." },
      { kind: "code", code: "s = Set()\ns.add(1)\ns.add(1)\nprint(s.size, s.has(1))" },
    ],
  },
  {
    id: "classes",
    title: "Classes & interfaces",
    group: "Language",
    summary: "Fields, accessors, statics, inheritance, and structural types.",
    blocks: [
      { kind: "text", text: "A `class` bundles data with behavior. Every member declares its visibility — `public`, `private`, or `protected` — and the `constructor` sets up `this`. Construct an instance by calling the class (the `new` keyword is optional)." },
      { kind: "code", code: "class Account:\n  public constructor(owner: string, balance: float = 0.0):\n    this.owner = owner\n    this.balance = balance\n  public deposit(amount: float) -> Account:\n    this.balance += amount\n    return this\n\nacc = Account(\"alice\")\nprint(acc.deposit(100.0).balance)" },
      { kind: "heading", text: "Getters & setters" },
      { kind: "text", text: "A `get` accessor exposes a computed property; a matching `set` accessor runs when the property is assigned." },
      { kind: "code", code: "class Temperature:\n  public constructor(celsius: float):\n    this.c = celsius\n  public get fahrenheit():\n    return this.c * 9.0 / 5.0 + 32.0\n  public set fahrenheit(f):\n    this.c = (f - 32.0) * 5.0 / 9.0\n\nt = Temperature(25.0)\nprint(t.fahrenheit)\nt.fahrenheit = 212.0\nprint(t.c)" },
      { kind: "heading", text: "Static members" },
      { kind: "text", text: "`static` members belong to the class itself rather than its instances — useful for shared state and factory methods." },
      { kind: "code", code: "class Config:\n  private static instance = Config(\"prod\")\n  private constructor(env):\n    this.env = env\n  public static get_instance():\n    return Config.instance\n  public describe() -> string:\n    return \"config:\" + this.env\n\na = Config.get_instance()\nb = Config.get_instance()\nprint(a.describe(), a === b)" },
      { kind: "heading", text: "Inheritance & abstract classes" },
      { kind: "text", text: "`extends` inherits members and `super` reaches the parent constructor. An `abstract` class cannot be constructed directly and may declare `abstract` methods that subclasses must implement." },
      { kind: "code", code: "class Shape:\n  public constructor(name: string):\n    this.name = name\n  public area() -> float:\n    return 0.0\n\nclass Circle extends Shape:\n  public constructor(r: float):\n    super(name=\"circle\")\n    this.r = r\n  public area() -> float:\n    return 3.14159 * this.r * this.r\n\nprint(Circle(2.0).area())" },
      { kind: "code", code: "abstract class LoggerApp:\n  public abstract make() -> string\n  public run() -> string:\n    return this.make()\n\nclass TextApp extends LoggerApp:\n  public make() -> string:\n    return \"text\"\n\nprint(TextApp().run())" },
      { kind: "heading", text: "Interfaces & type aliases" },
      { kind: "text", text: "An `interface` describes the shape of an object; `type` names a reusable type; a trailing `?` marks a field optional. Typing is structural, and a class can declare `implements` to be checked against an interface." },
      { kind: "code", code: "type UserId = int | string\n\ninterface User:\n  id: UserId\n  name: string\n  active?: bool\n\nada: User = { id: 1, name: \"Ada\" }\nprint(ada.name)" },
      { kind: "code", code: "interface Logger:\n  log(message: string) -> string\n\nclass TextLogger implements Logger:\n  public log(message: string) -> string:\n    return \"log: \" + message\n\nprint(TextLogger().log(\"hi\"))" },
    ],
  },
  {
    id: "async",
    title: "Async & generators",
    group: "Language",
    summary: "async functions, await, promises, and generators.",
    blocks: [
      { kind: "text", text: "A function that uses `await` is `async` — mark it with `async fn`. `await` suspends until a promise settles and yields its value." },
      { kind: "code", code: "async fn fetch_user(id: int):\n  return { id: id, name: `user-${id}` }\n\nasync fn greet(id: int) -> string:\n  user = await fetch_user(id)\n  return \"hello \" + user.name\n\nasync fn main() -> void:\n  print(await greet(7))\n\nmain()" },
      { kind: "text", text: "Errors from an awaited call propagate like any other throw, so `try`/`catch` handles them." },
      { kind: "code", code: "async fn safe(a: float, b: float) -> float:\n  if b == 0.0:\n    throw \"div by zero\"\n  return a / b\n\nasync fn run() -> void:\n  try:\n    print(await safe(10.0, 2.0))\n    print(await safe(1.0, 0.0))\n  catch e:\n    print(\"caught:\", e)\n\nrun()" },
      { kind: "heading", text: "Promises" },
      { kind: "text", text: "`Promise.resolve` wraps a value; `then` chains transformations; `Promise.all` waits for several promises at once." },
      { kind: "code", code: "Promise.resolve(10).then(v => v * 2).then(v => v + 1).then(v => print(v))" },
      { kind: "code", code: "async fn go() -> void:\n  rs = await Promise.all([Promise.resolve(1), Promise.resolve(2)])\n  print(rs)\n\ngo()" },
      { kind: "heading", text: "Generators" },
      { kind: "text", text: "`fn*` declares a generator: each `yield` produces a value, and the generator can be iterated with `for … of`." },
      { kind: "code", code: "fn* gen():\n  yield 1\n  yield 2\n  yield 3\n\nfor v of gen():\n  print(v)" },
    ],
  },
  {
    id: "namespaces",
    title: "Built-in namespaces",
    group: "Language",
    summary: "Math and JSON helpers.",
    blocks: [
      { kind: "text", text: "`Math` collects numeric helpers and constants." },
      { kind: "code", code: "print(Math.abs(-5), Math.floor(2.7), Math.ceil(2.1), Math.round(2.5))\nprint(Math.pow(2, 10), Math.sqrt(81), Math.min(3, 1, 2), Math.max(3, 1, 2))\nprint(Math.PI, Math.E)" },
      { kind: "text", text: "`Math.random` returns a float in `[0, 1)` — compose it for dice rolls and samples." },
      { kind: "code", code: "roll = Math.floor(Math.random() * 6) + 1\nprint(roll >= 1 and roll <= 6)" },
      { kind: "text", text: "`JSON.stringify` and `JSON.parse` convert between values and their JSON text." },
      { kind: "code", code: "text = JSON.stringify({ a: 1, b: [2, 3] })\nprint(text)\nprint(JSON.parse(text).a)" },
    ],
  },
  {
    id: "tensors",
    title: "Tensors",
    group: "Extensions",
    summary: "N-dimensional arrays, shapes, math, reductions, and gradients.",
    blocks: [
      { kind: "text", text: "Tensors are n-dimensional numeric arrays. Build them from literals or with factories like `zeros`, `ones`, `full`, `eye`, `arange`, `linspace`, `randn`, and `randperm`. `to_array` reads a tensor into nested arrays, and `item` extracts a single scalar." },
      { kind: "code", code: "a = tensor([[1, 2], [3, 4]])\nprint(a.shape)\nprint(zeros([2, 2]).shape, ones([3]).shape, eye(2).shape)" },
      { kind: "code", code: "print(full([2, 2], 7).to_array())\nprint(linspace(0.0, 1.0, 5).to_array())\nprint(randn([2, 3]).shape)" },
      { kind: "heading", text: "Shape & layout" },
      { kind: "text", text: "`reshape`, `transpose`, `permute`, `unsqueeze`, and `squeeze` rearrange a tensor without copying its data. `ndim` and `numel` describe it." },
      { kind: "code", code: "print(arange(0, 6).reshape([2, 3]).shape)\nprint(tensor([[1, 2, 3], [4, 5, 6]]).transpose(0, 1).shape)\nprint(zeros([2, 3, 4]).permute([2, 0, 1]).shape)" },
      { kind: "code", code: "print(tensor([1.0, 2.0]).unsqueeze(0).shape)\nprint(zeros([1, 3]).squeeze(0).shape)\nprint(zeros([2, 3]).ndim, zeros([2, 3]).numel)" },
      { kind: "heading", text: "Elementwise math" },
      { kind: "text", text: "Scalars broadcast, and unary math and activations apply elementwise. `@` is the matrix product." },
      { kind: "code", code: "print((tensor([1.0, 2.0]) + 10.0).to_array())\nprint(tensor([1.0, 2.0, 3.0]).pow(2.0).to_array())\nprint(tensor([-2.0]).abs().item(), tensor([2.0]).neg().item())" },
      { kind: "code", code: "print(tensor([-1.0, 2.0, -3.0]).relu().to_array())\nprint(tensor([1.0, 2.0, 3.0]).softmax(-1).to_array())" },
      { kind: "code", code: "a = tensor([[1.0, 2.0], [3.0, 4.0]])\nb = eye(2)\nprint((a @ b).to_array())" },
      { kind: "heading", text: "Comparisons & reductions" },
      { kind: "text", text: "Comparison methods return boolean tensors; reductions such as `sum`, `mean`, `max`, `argmax`, and `prod` collapse a tensor." },
      { kind: "code", code: "print(tensor([1.0, 2.0]).gt(tensor([0.0, 3.0])).to_array())\nprint(tensor([1.0, 2.0, 3.0, 4.0]).mean().item())\nprint(tensor([1.0, 5.0, 3.0]).max().item(), tensor([1.0, 5.0, 3.0]).argmax().item())" },
      { kind: "text", text: "Combine tensors with `cat` (existing axis), `stack` (new axis), and `where` (elementwise choice)." },
      { kind: "code", code: "print(cat([tensor([1.0]), tensor([2.0])]).to_array())\nprint(stack([tensor([1.0]), tensor([2.0])]).shape)\nprint(where(tensor([true, false]), tensor([1.0, 1.0]), tensor([9.0, 9.0])).to_array())" },
      { kind: "heading", text: "Automatic gradients" },
      { kind: "text", text: "Create a tensor with `grad=true` to track operations on it. After computing a scalar, call `backward` to populate `.grad` with the derivatives — the foundation training is built on. `detach` returns a copy outside the gradient graph." },
      { kind: "code", code: "x = tensor([1.0, 2.0, 3.0], grad=true)\ny = (x * x).sum()\ny.backward()\nprint(x.grad.to_array())" },
      { kind: "code", code: "print(tensor([1.0, 2.0], grad=true).detach().to_array())" },
    ],
  },
  {
    id: "models",
    title: "Models & neural networks",
    group: "Extensions",
    summary: "Layers, forward passes, optimizers, and training.",
    wip: true,
    blocks: [],
  },
  {
    id: "dataframes",
    title: "DataFrames",
    group: "Extensions",
    summary: "Columnar tables with a lazy, composable query API.",
    blocks: [
      { kind: "text", text: "A `DataFrame` is a columnar table. Build one by passing named columns, then call `show` to print it. `columns` lists the column names." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[10, 20, 30])\ndf.show()" },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\"], value=[10, 20])\nprint(df.columns())" },
      { kind: "heading", text: "Selecting & filtering" },
      { kind: "text", text: "Queries are built by chaining transformations. `select` keeps columns; `filter` keeps rows, where `col(\"name\")` refers to a column and carries comparisons like `gt`, `lt`, and `eq`." },
      { kind: "code", code: "df = DataFrame(a=[1, 2], b=[3, 4], c=[5, 6])\ndf.select(\"a\", \"c\").show()" },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[10, 20, 30])\ndf.filter(col(\"value\").gt(10)).show()" },
      { kind: "heading", text: "Derived columns" },
      { kind: "text", text: "`with_column` adds a computed column from a column expression — `add`, `sub`, `mul`, and `div` build arithmetic, and `alias`/`as` rename." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\"], value=[10, 20])\ndf.with_column(\"double\", col(\"value\").mul(2)).show()" },
      { kind: "heading", text: "Grouping & aggregation" },
      { kind: "text", text: "`group_by(...).agg(...)` collapses groups with aggregates such as `sum`, `avg`, `min`, `max`, and `count`, each usually renamed with `alias`." },
      { kind: "code", code: "df = DataFrame(group=[\"a\", \"a\", \"b\"], value=[1, 2, 3])\ndf.group_by(\"group\").agg(sum(col(\"value\")).alias(\"total\")).show()" },
      { kind: "code", code: "df = DataFrame(g=[\"a\", \"a\", \"b\"], v=[1, 2, 3])\ndf.group_by(\"g\").agg(sum(col(\"v\")).alias(\"sum\"), avg(col(\"v\")).alias(\"avg\")).show()" },
      { kind: "heading", text: "Ordering & slicing" },
      { kind: "text", text: "`order_by` sorts, `limit` and `head` take a prefix, and `distinct` drops duplicate rows." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[30, 10, 20])\ndf.order_by(\"value\").show()" },
      { kind: "code", code: "df = DataFrame(x=[1, 1, 2, 2, 3])\ndf.limit(2).show()\ndf.distinct().show()" },
      { kind: "text", text: "Transformations compose into a single query and only run when you display or collect it." },
      { kind: "code", code: "df = DataFrame(name=[\"A\", \"B\", \"C\"], value=[10, 20, 30])\ndf.filter(col(\"value\").gt(10)).with_column(\"double\", col(\"value\").mul(2)).order_by(\"value\").show()" },
      { kind: "heading", text: "Pulling results" },
      { kind: "text", text: "A DataFrame is lazy and its terminal operations are asynchronous: `await` `count` for the row count, `collect` for the rows, and `to_tensor` to move numeric columns into a tensor." },
      { kind: "code", code: "async fn summary() -> void:\n  df = DataFrame(a=[1, 2, 3], b=[4.0, 5.0, 6.0])\n  print(await df.count())\n  rows = await df.collect()\n  print(rows)\n\nsummary()" },
      { kind: "code", code: "async fn to_matrix() -> void:\n  df = DataFrame(a=[1.0, 2.0], b=[3.0, 4.0])\n  t = await df.to_tensor()\n  print(t.shape)\n\nto_matrix()" },
    ],
  },
  {
    id: "charts",
    title: "Charts",
    group: "Extensions",
    summary: "Turning data into inline visualizations.",
    wip: true,
    blocks: [],
  },
  {
    id: "quant",
    title: "Quant & finance",
    group: "Extensions",
    summary: "Backtesting, signals, portfolios, and risk metrics.",
    wip: true,
    blocks: [],
  },
  {
    id: "reactivity",
    title: "Reactivity",
    group: "Extensions",
    summary: "Signals, computed values, effects, and batching.",
    blocks: [
      { kind: "text", text: "Reactive bindings track values that change over time. A `signal` holds writable state; a `computed` derives a value from other reactive reads and updates itself when they do. Inside reactive code you read a binding by its name." },
      { kind: "code", code: "signal clicks = 0\ncomputed doubled = clicks * 2\nclicks.set(3)\nprint(doubled)" },
      { kind: "text", text: "Update a signal with `set`, or with `update` to derive the next value from the current one. `peek` reads the value without subscribing." },
      { kind: "code", code: "signal n = 1\nn.update(v => v + 41)\nprint(n)\nprint(n.peek())" },
      { kind: "text", text: "An `effect:` block re-runs whenever any reactive value it reads changes — the place for side effects like logging or drawing." },
      { kind: "code", code: "signal name = \"Ada\"\neffect:\n  print(\"hello\", name)\nname.set(\"Grace\")" },
      { kind: "text", text: "`batch` groups several writes so dependents recompute once, after the batched function returns." },
      { kind: "code", code: "signal a = 1\nsignal b = 2\ncomputed s = a + b\n\nfn bump():\n  a.set(10)\n  b.set(20)\n\nbatch(bump)\nprint(s)" },
      { kind: "text", text: "A `resource` wraps asynchronous data and tracks its loading and error state, so views can react to each phase." },
      { kind: "code", code: "resource user = Promise.resolve({ name: \"Ada\" })\nprint(user.loading)" },
    ],
  },
];
