import {
  TERA_ALLOC_SYMBOL,
  TERA_ARRAY_RESERVE_SYMBOL,
  TERA_COLLECT_SYMBOL,
  TERA_ENTER_ROOTS_SYMBOL,
  TERA_GROW_SYMBOL,
  TERA_RESERVE_SYMBOL,
} from "../../target/runtime-layout.js";
export const X64_RUNTIME_SYMBOLS = {
  toInt32: "tera_x64_to_i32",
  divide: "tera_x64_i32_div",
  modulo: "tera_x64_i32_mod",
  minimum: "tera_x64_math_min",
  maximum: "tera_x64_math_max",
  charCodeAt: "tera_x64_char_code_at",
  stringSet: "tera_x64_str_set",
  stringAppend: "tera_x64_str_append",
  charAt: "tera_x64_char_at",
  int32ToString: "tera_x64_i32_to_str",
  stringLength: "tera_x64_strlen",
  stringCompare: "tera_x64_strcmp",
  printString: "tera_x64_print_str",
  printInt: "tera_x64_print_i32",
  printFloat: "tera_x64_print_f64",
  input: "tera_x64_input",
  throwError: "tera_x64_throw",
  bignumSet: "tera_x64_bn_set",
  bignumCopy: "tera_x64_bn_copy",
  bignumMultiply: "tera_x64_bn_mul",
  bignumShift: "tera_x64_bn_shl",
  bignumCompare: "tera_x64_bn_cmp",
  bignumSubtract: "tera_x64_bn_sub",
  bignumAdd: "tera_x64_bn_add",
  floatToString: "tera_x64_f64_to_str",
  stringUpper: "tera_x64_str_upper",
  stringLower: "tera_x64_str_lower",
  stringTrim: "tera_x64_str_trim",
  stringTrimStart: "tera_x64_str_trim_start",
  stringTrimEnd: "tera_x64_str_trim_end",
  stringSlice: "tera_x64_str_slice",
  stringRepeat: "tera_x64_str_repeat",
  stringReplace: "tera_x64_str_replace",
  stringReplaceAll: "tera_x64_str_replace_all",
  stringIndexOf: "tera_x64_str_index_of",
  stringIncludes: "tera_x64_str_includes",
  stringStartsWith: "tera_x64_str_starts_with",
  stringEndsWith: "tera_x64_str_ends_with",
  parseInt: "tera_x64_parse_int",
  parseFloat: "tera_x64_parse_float",
  allocate: TERA_ALLOC_SYMBOL,
  arrayReserve: TERA_ARRAY_RESERVE_SYMBOL,
  collect: TERA_COLLECT_SYMBOL,
  enterRoots: TERA_ENTER_ROOTS_SYMBOL,
  reserve: TERA_RESERVE_SYMBOL,
  grow: TERA_GROW_SYMBOL,
  markPass: "tera_x64_mark_pass",
  sweep: "tera_x64_sweep",
  take: "tera_x64_take",
} as const;

export const X64_PROGRAM_ENTRY = "_start";
