export type Sample = {
  readonly id: string;
  readonly label: string;
  readonly hint: string;
  readonly source: string;
};

export const SAMPLES: readonly Sample[] = [
  {
    id: "counted-loop",
    label: "Counted loop",
    hint: "licm lifts the two constants out of the loop; strength-reduction turns i * 3 into a shift plus an add, and the node count goes up",
    source: [
      "fn work(n: int) -> int:",
      "  total = 0",
      "  i = 0",
      "  while (i < n):",
      "    total = (total + (i * 3))",
      "    i = (i + 1)",
      "  return total",
      "",
      "print(work(400))",
    ].join("\n"),
  },
  {
    id: "indexed-loop",
    label: "Indexed loop",
    hint: "gvn shares the repeated subexpression; the CheckBounds that survives is worth reading",
    source: [
      "fn total(rounds: int) -> int:",
      "  xs = [3, 1, 4, 1, 5, 9, 2, 6]",
      "  acc = 0",
      "  r = 0",
      "  while (r < rounds):",
      "    i = 0",
      "    while (i < xs.length):",
      "      acc = (acc + xs[i] + (i * 3 + 1) + (i * 3 + 1))",
      "      i = (i + 1)",
      "    r = (r + 1)",
      "  return acc",
      "",
      "print(total(60))",
    ].join("\n"),
  },
  {
    id: "branching-call",
    label: "Branching call",
    hint: "type-narrowing is the one to read: once the branch proves the type, the generic compare and subtract become int32 ones",
    source: [
      "fn pick(n: int) -> int:",
      "  if (n > 10):",
      "    return (n * 2)",
      "  return (n - 1)",
      "",
      "fn drive(n: int) -> int:",
      "  last = 0",
      "  i = 0",
      "  while (i < n):",
      "    last = pick(i)",
      "    i = (i + 1)",
      "  return last",
      "",
      "print(drive(400))",
    ].join("\n"),
  },
  {
    id: "escaping-object",
    label: "Object in a loop",
    hint: "load-elimination forwards both field reads and dead-store-elimination drops the writes — yet the NewObject survives, because the loop phi for `point` still names the object the iteration before built, and a deopt frame can record only one rebuild per allocation site. Compare with \"Object per iteration\"",
    source: [
      "fn total(n: int) -> int:",
      "  acc = 0",
      "  i = 0",
      "  while (i < n):",
      "    point = { x: i, y: (i * 2) }",
      "    acc = (acc + point.x + point.y)",
      "    i = (i + 1)",
      "  return acc",
      "",
      "print(total(300))",
    ].join("\n"),
  },
  {
    id: "sunk-object",
    label: "Object per iteration",
    hint: "the same object, with no local to carry it across the backedge: escape-analysis-late scalar replaces it and the loop body ends up pure arithmetic — no NewObject, no CheckMap, no StoreField",
    source: [
      "fn total(n: int) -> int:",
      "  acc = 0",
      "  i = 0",
      "  while (i < n):",
      "    acc = (acc + { x: i, y: (i * 2) }.x)",
      "    i = (i + 1)",
      "  return acc",
      "",
      "print(total(300))",
    ].join("\n"),
  },
  {
    id: "polymorphic",
    label: "Polymorphic call site",
    hint: "JIT only — shape is untyped, so AOT refuses it. Open Runtime and watch the inline cache go monomorphic then polymorphic",
    source: [
      "fn area(shape) -> float:",
      "  return shape.w * shape.h",
      "",
      "fn drive(n: int) -> float:",
      "  acc = 0.0",
      "  i = 0",
      "  while (i < n):",
      "    if (i % 2) == 0:",
      "      acc = acc + area({ w: 2.0, h: 3.0 })",
      "    else:",
      "      acc = acc + area({ w: 2.0, h: 3.0, label: \"tall\" })",
      "    i = (i + 1)",
      "  return acc",
      "",
      "print(drive(200))",
    ].join("\n"),
  },
  {
    id: "async-await",
    label: "Async function",
    hint: "produce collects feedback like any function and the JIT still returns no graph for it; AOT splits it into a frame plus a step function",
    source: [
      "async fn produce(n: int) -> int:",
      "  return (n + 1)",
      "",
      "fn drive(n: int) -> int:",
      "  last = 0",
      "  i = 0",
      "  while (i < n):",
      "    last = i",
      "    i = (i + 1)",
      "  produce(last)",
      "  return last",
      "",
      "print(drive(200))",
    ].join("\n"),
  },
  {
    id: "aot-ready",
    label: "AOT-ready arithmetic",
    hint: "every parameter is declared, so the AOT backends can compile it",
    source: [
      "fn add(a: int, b: int) -> int:",
      "  return a + b",
      "",
      "fn main() -> int:",
      "  total = 0",
      "  i = 0",
      "  while (i < 100):",
      "    total = add(total, i)",
      "    i = (i + 1)",
      "  return total",
      "",
      "print(main())",
    ].join("\n"),
  },
];
