import {
  TERA_ALLOC_SYMBOL,
  TERA_ARRAY_RESERVE_SYMBOL,
  TERA_COLLECT_SYMBOL,
  TERA_ENTER_ROOTS_SYMBOL,
  TERA_PROBE_STACK_SYMBOL,
  TERA_GROW_SYMBOL,
  TERA_RESERVE_SYMBOL,
} from "../../target/runtime-layout.js";

export const RISCV_RUNTIME_SYMBOLS = {
  toInt32: "tera_rv64_to_i32",
  divide: "tera_rv64_i32_div",
  modulo: "tera_rv64_i32_mod",
  minimum: "tera_rv64_math_min",
  maximum: "tera_rv64_math_max",
  charCodeAt: "tera_rv64_char_code_at",
  stringSet: "tera_rv64_str_set",
  stringAppend: "tera_rv64_str_append",
  charAt: "tera_rv64_char_at",
  int32ToString: "tera_rv64_i32_to_str",
  stringLength: "tera_rv64_strlen",
  stringCompare: "tera_rv64_strcmp",
  floor: "tera_rv64_math_floor",
  ceil: "tera_rv64_math_ceil",
  trunc: "tera_rv64_math_trunc",
  printString: "tera_rv64_print_str",
  printInt: "tera_rv64_print_i32",
  input: "tera_rv64_input",
  printFloat: "tera_rv64_print_f64",
  bignumSet: "tera_rv64_bn_set",
  bignumCopy: "tera_rv64_bn_copy",
  bignumMultiply: "tera_rv64_bn_mul",
  bignumShift: "tera_rv64_bn_shl",
  bignumCompare: "tera_rv64_bn_cmp",
  bignumSubtract: "tera_rv64_bn_sub",
  bignumAdd: "tera_rv64_bn_add",
  floatToString: "tera_rv64_f64_to_str",
  throwError: "tera_rv64_throw",
  allocate: TERA_ALLOC_SYMBOL,
  arrayReserve: TERA_ARRAY_RESERVE_SYMBOL,
  collect: TERA_COLLECT_SYMBOL,
  enterRoots: TERA_ENTER_ROOTS_SYMBOL,
  probeStack: TERA_PROBE_STACK_SYMBOL,
  reserve: TERA_RESERVE_SYMBOL,
  grow: TERA_GROW_SYMBOL,
  markPass: "tera_rv64_mark_pass",
  sweep: "tera_rv64_sweep",
  take: "tera_rv64_take",
} as const;

export const RISCV_PROGRAM_ENTRY = "_start";
