export * from "./index.browser.js";
export { compileModule } from "./optimizing/drivers/aot.js";
export type { AotDriverOptions, AotProgram, AotSkippedFunction } from "./optimizing/drivers/aot.js";
export { writeAotProgram } from "./optimizing/drivers/write.js";
export { createBackendRegistry } from "./optimizing/backends/index.js";
export { consoleMachineTracer, formatMachineTrace } from "./optimizing/machine/trace.js";
export type { MachineTraceRecord, MachineTracer } from "./optimizing/machine/trace.js";
export { consoleModuleTracer, formatModuleTrace, printModuleIR } from "./optimizing/drivers/module-trace.js";
export type { ModuleTraceRecord, ModuleTracer } from "./optimizing/drivers/module-trace.js";
export { hostBackendId, HOST_PLATFORM } from "./optimizing/backends/host.js";
export type { AotBackend } from "./optimizing/target/backend.js";
export { nodeModuleFileSystem } from "./frontend/modules/node-file-system.js";
