export { Engine } from "./api/engine.js";
export type { AotCompileOptions, AotFunctionCompileOptions, EngineOptions, CompileOptions, EngineValue, EngineUnhandledRejection } from "./api/engine.js";
export { createJitBackendRegistry, resolveJitBackend } from "./optimizing/backends/jit.js";
export { createBackendRegistry } from "./optimizing/backends/index.js";
export { isAotBackend } from "./optimizing/target/backend.js";
export type { AotBackend, CodeBackend, TargetPlatform } from "./optimizing/target/backend.js";
export { compilerOptions, DEFAULT_COMPILER_OPTIONS } from "./optimizing/options.js";
export type { CompilerOptions, OptLevel } from "./optimizing/options.js";
export { IR_BUILDER_STAGE, middleEndPhases, middleEndPipeline } from "./optimizing/pipeline.js";
export { printIR, parseIR, IRTextError } from "./optimizing/ir/text.js";
export { cfgGraphProbe } from "./optimizing/ir/probe.js";
export { afterPass, afterNamedPass, runNamedPass, analysesFor, middleEndPassNames, passByName, UnknownPassError } from "./optimizing/drivers/text-driver.js";
export type { NamedPassOutcome } from "./optimizing/drivers/text-driver.js";
export { consolePassTracer, formatPassTrace, formatRemark } from "./optimizing/infra/pass-trace.js";
export { OptBisect } from "./optimizing/infra/opt-bisect.js";
export { VerificationError } from "./optimizing/infra/pass-manager.js";
export { REMARK_BUDGET } from "./optimizing/infra/pass-remarks.js";
export type { Remark, RemarkKind } from "./optimizing/infra/pass-remarks.js";
export { consoleMachineTracer, formatMachineTrace } from "./optimizing/machine/trace.js";
export type { MachineTraceRecord, MachineTracer } from "./optimizing/machine/trace.js";
export { printMachineFunction } from "./optimizing/machine/print.js";
export { allocationReport, registerName } from "./optimizing/machine/allocation-report.js";
export type { AllocationBlockReport, AllocationInstructionReport, AllocationIntervalReport, AllocationRangeReport, AllocationReport, AllocationTracer } from "./optimizing/machine/allocation-report.js";
export { consoleModuleTracer, formatModuleTrace, printModuleIR } from "./optimizing/drivers/module-trace.js";
export type { ModuleTraceRecord, ModuleTracer } from "./optimizing/drivers/module-trace.js";
export type { GraphProbe, PassTraceRecord, PassTracer, PassTracing } from "./optimizing/infra/pass-trace.js";
export type { CFGBlock, CFGFunction, CFGInstruction, IRSourcePosition } from "./optimizing/ir/index.js";
export { BackendRegistry, UnknownBackendError } from "./optimizing/target/registry.js";
export { createCompilationUnit, createModuleIR, moduleFromGraphs } from "./optimizing/compilation-unit.js";
export type { CompilationUnit, ModuleIR } from "./optimizing/compilation-unit.js";
export { mergeCompilerExtensions, resolveTeraExtensions } from "./api/extensions.js";
export type { NativeHostBuiltin, NativeHostBuiltinRegistry, ResolvedTeraExtensions, TeraCompilerEffect, TeraCompilerExtension, TeraCompilerPhase, TeraDeoptSpec, TeraEffectMetadata, TeraExtension, TeraGuardKind, TeraGuardSpec, TeraIntrinsicSpec, TeraOptimizerPass, TeraOptimizerPassContext } from "./api/extensions.js";
export { DebugController, TeraDebugSession } from "./debugger/index.js";
export type { DebugBindingSnapshot, DebugBreakpoint, DebugCommand, DebugFrameSnapshot, DebugPauseEvent, DebugPauseReason, DebugPropertySnapshot, DebugSnapshot, DebugSourceLocation, DebugValueSnapshot, RuntimeDebugger, TeraDebugSessionOptions } from "./debugger/index.js";
export { buildSourceSymbolTable, checkSource, diagnoseSource, inferSymbolTypes, TypecheckError } from "./frontend/checker/index.js";
export type { BindOptions, CheckSourceOptions, Diagnostic, ExternalBuiltinParam, ExternalBuiltinSignature, ExternalInterface, ExternalInterfaceField, ExternalTypeAlias, ScopeKind, SourceScope, SourceSymbol, SourceSymbolTable, SymbolKind, SymbolPosition, TypecheckMode, SymbolType } from "./frontend/checker/index.js";
export type { ModuleFileSystem } from "./frontend/modules/file-system.js";
export { recoverMemberCompletionSource } from "./frontend/editor-analysis.js";
export { tokenize } from "./frontend/lexer/offside.js";
export type { Token, TokenValue } from "./frontend/lexer/index.js";
export { KEYWORDS } from "./frontend/lexer/index.js";
export { parse } from "./frontend/parser/language.js";
export { printAst } from "./frontend/ast-text.js";
export type { ASTNode, NodeTypeName } from "./frontend/index.js";
export type { ParserCheckpoint, ParserContext, ParserOptions, StatementParseResult, SyntaxPlugin, SyntaxTransformContext } from "./frontend/index.js";
export { applySyntaxTransforms } from "./frontend/index.js";
export { hostBuiltin, nativeToTagged, taggedToNative } from "./runtime/domain/host.js";
export { installBuiltinEntries } from "./runtime/builtins/index.js";
export type { BuiltinGlobalCells, BuiltinRegistryEntry, BuiltinRegistryMap } from "./runtime/builtins/index.js";
export type { RuntimeFunctionPayload, TaggedValue } from "./core/value/index.js";
export { TERA_BUILTINS, TERA_CHART_METHODS } from "../data/tera-language-spec.js";
