export { Engine } from "./api/engine.js";
export type { AotCompileOptions, AotFunctionCompileOptions, EngineOptions, CompileOptions, EngineValue, EngineUnhandledRejection } from "./api/engine.js";
export { compileModule, writeAotProgram } from "./optimizing/drivers/aot.js";
export type { AotDriverOptions, AotProgram, AotSkippedFunction } from "./optimizing/drivers/aot.js";
export { createCompilationUnit, createModuleIR, moduleFromGraphs } from "./optimizing/compilation-unit.js";
export type { CompilationUnit, ModuleIR } from "./optimizing/compilation-unit.js";
export type { AotBackend } from "./optimizing/target/backend.js";
export { mergeCompilerExtensions, resolveTeraExtensions } from "./api/extensions.js";
export type { NativeHostBuiltin, NativeHostBuiltinRegistry, ResolvedTeraExtensions, TeraCompilerEffect, TeraCompilerExtension, TeraCompilerPhase, TeraDeoptSpec, TeraEffectMetadata, TeraExtension, TeraGuardKind, TeraGuardSpec, TeraIntrinsicSpec, TeraOptimizerPass, TeraOptimizerPassContext } from "./api/extensions.js";
export { DebugController, TeraDebugSession } from "./debugger/index.js";
export type { DebugBindingSnapshot, DebugBreakpoint, DebugCommand, DebugFrameSnapshot, DebugPauseEvent, DebugPauseReason, DebugPropertySnapshot, DebugSnapshot, DebugSourceLocation, DebugValueSnapshot, RuntimeDebugger, TeraDebugSessionOptions } from "./debugger/index.js";
export { buildSourceSymbolTable, checkSource, diagnoseSource, inferSymbolTypes, TypecheckError } from "./frontend/checker/index.js";
export type { BindOptions, CheckSourceOptions, Diagnostic, ExternalBuiltinParam, ExternalBuiltinSignature, ExternalInterface, ExternalInterfaceField, ExternalTypeAlias, ScopeKind, SourceScope, SourceSymbol, SourceSymbolTable, SymbolKind, SymbolPosition, TypecheckMode, SymbolType } from "./frontend/checker/index.js";
export { recoverMemberCompletionSource } from "./frontend/editor-analysis.js";
export { tokenize } from "./frontend/lexer/offside.js";
export { KEYWORDS } from "./frontend/lexer/index.js";
export { parse } from "./frontend/parser/language.js";
export type { ASTNode, NodeTypeName } from "./frontend/index.js";
export type { ParserCheckpoint, ParserContext, ParserOptions, StatementParseResult, SyntaxPlugin, SyntaxTransformContext } from "./frontend/index.js";
export { applySyntaxTransforms } from "./frontend/index.js";
export { hostBuiltin, nativeToTagged, taggedToNative } from "./runtime/domain/host.js";
export { installBuiltinEntries } from "./runtime/builtins/index.js";
export type { BuiltinGlobalCells, BuiltinRegistryEntry, BuiltinRegistryMap } from "./runtime/builtins/index.js";
export type { RuntimeFunctionPayload, TaggedValue } from "./core/value/index.js";
export { TERA_BUILTINS, TERA_CHART_METHODS } from "../data/tera-language-spec.js";
